version: '3.7'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/workspace/nse
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - celery
      - mailcatcher
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3305:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=hello_django
      - MYSQL_DATABASE=db
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
    expose:
      - 6379
  mailcatcher:
    image: schickling/mailcatcher:latest
    command: mailcatcher --no-quit --foreground --ip=0.0.0.0
    ports:
      - 1026:1025
      - 1081:1080
  celery:
    build: .
    command: celery -A nse worker -l info
    volumes:
      - .:/home/workspace/nse
    depends_on:
      - db
      - redis

volumes:
  mysql_data: