# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-20 11:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='stock',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('price', models.FloatField(default=0.0)),
                ('max_price_of_day', models.FloatField(default=0.0)),
                ('stock_Exchange', models.CharField(default='NYSE', max_length=10)),
                ('update', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='userstock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.CharField(default='', max_length=10000)),
                ('balance', models.FloatField(default=1000000.0)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
